### ISSUE TITLE
downloading

### ISSUE THREAD

**Issue by GlacierShard92** [Blubberboy333/CrateKeys#1]
can u add a CrateKeys.phar to download? This looks like a good plugin to use, but i can't install it as it is now :(

**Comment by Blubberboy333** [comment]
I will add a phar file as soon as I'm done making this plugin

**Comment by GlacierShard92** [comment]
thank you!!! :D

**Comment by XoticRealmsOwnerandDev** [comment]
blubber help me with the kit plugin i sent a few msgs on kik.

**Comment by Blubberboy333** [comment]
Alright, do you want me to stop working on this for now and start making a kits plugin?

**Comment by Blubberboy333** [comment]
I finished the coding of this plugin, but it will most likely have a lot of bugs or won't work. If you have any problems, please open a new issue and let me know what is wrong. You can download the untested version from [here](https://github.com/Blubberboy333/CrateKeys/releases)
